version: '3.5'

services:
  DATABASE:
    image: postgres
    restart: always
    container_name: weather-db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
    - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - DATABASE
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: weather-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - DATABASE